from setuptools import setup, find_packages

setup(
    name="your_project_name",
    version="1.0.0",
    description="A brief description of your project",
    author="Your Name",
    author_email="your.email@example.com",
    python_requires=">=3.12",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "appnope==0.1.4",
        "asttokens==2.4.1",
        "backcall==0.2.0",
        "comm==0.2.2",
        "contourpy==1.1.1",
        "cycler==0.12.1",
        "debugpy==1.8.1",
        "decorator==5.1.1",
        "executing==2.0.1",
        "fonttools==4.50.0",
        "importlib-metadata==7.1.0",
        "importlib-resources==6.4.0",
        "ipykernel==6.29.4",
        "ipython==8.12.3",
        "jedi==0.19.1",
        "joblib==1.3.2",
        "jupyter-client==8.6.1",
        "jupyter-core==5.7.2",
        "kiwisolver==1.4.5",
        "matplotlib==3.7.5",
        "matplotlib-inline==0.1.7",
        "nest-asyncio==1.6.0",
        "numpy>=1.26",
        "packaging==24.0",
        "pandas==2.2.2",
        "parso==0.8.4",
        "patsy==0.5.6",
        "pexpect==4.9.0",
        "pickleshare==0.7.5",
        "pillow==10.3.0",
        "platformdirs==4.2.0",
        "prompt-toolkit==3.0.43",
        "psmpy==0.3.13",
        "psutil==5.9.8",
        "ptyprocess==0.7.0",
        "pure-eval==0.2.2",
        "pygments==2.17.2",
        "pyparsing==3.1.2",
        "python-dateutil==2.9.0.post0",
        "pytz==2024.1",
        "pyzmq==26.0.0",
        "rpy2==3.5.17",
        "scikit-learn==1.3.2",
        "scipy==1.15.0",
        "seaborn==0.13.2",
        "six==1.16.0",
        "stack-data==0.6.3",
        "statsmodels==0.14.1",
        "threadpoolctl==3.4.0",
        "tornado==6.4",
        "traitlets==5.14.2",
        "typing-extensions==4.11.0",
        "tzdata==2024.1",
        "wcwidth==0.2.13",
        "zipp==3.18.1",
    ],
    classifiers=[
        "Programming Language :: Python :: 3.12",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
