name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - documentation
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/docs/requirements.txt
          sudo apt-get install -y make

      - name: Build Sphinx HTML
        run: sphinx-build -b html source build/html
        working-directory: src/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/docs/build/html
